from flask_wtf import FlaskForm 
from wtforms import SelectField, SubmitField
from wtforms.validators import DataRequired

class chartForm(FlaskForm):
    statType = SelectField('Stat Selection', choices=[('pts', 'Points Per Game'), ('per','Player Efficiency Rating'), ('reb','Rebounds Per Game'), ('ast','Assists Per Game'), ('stl', 'Steals Per Game'), ('blk', 'Blocks Per Game'), ('fg%', 'Field Goal Percentage'), ('3p%', '3-Point Percentage')], validators=[DataRequired()])
    chartType = SelectField('Chart Type Selection', choices=['Bar-Graph', 'Scatter-Plot', 'Line-Graph'], validators=[DataRequired()])
    submit = SubmitField()

class compareForm(FlaskForm):
    player1 = SelectField('Player 1 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player2 = SelectField('Player 2 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player3 = SelectField('Player 3 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player4 = SelectField('Player 4 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player5 = SelectField('Player 5 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    statType = SelectField('Stat Selection', choices=[('pts', 'Points Per Game'), ('per','Player Efficiency Rating'), ('reb','Rebounds Per Game'), ('ast','Assists Per Game'), ('stl', 'Steals Per Game'), ('blk', 'Blocks Per Game'), ('fg%', 'Field Goal Percentage'), ('3p%', '3-Point Percentage')], validators=[DataRequired()])
    submit = SubmitField()

class lineupForm(FlaskForm):
    player1 = SelectField('Player 1 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player2 = SelectField('Player 2 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player3 = SelectField('Player 3 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player4 = SelectField('Player 4 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    player5 = SelectField('Player 5 Selection', choices=[('Embiid','Joel Embiid'), ('Antetokounmpo','Giannis Antetokounmpo'), ('Doncic','Luka Doncic'), ('Young','Trae Young'), ('DeRozan','DeMar DeRozan'), ('Jokic','Nikola Jokic'), ('Tatum','Jayson Tatum'), ('Booker','Devin Booker'), ('James','LeBron James'), ('Durant','Kevin Durant'), ('Gobert','Rudy Gobert'), ('Morant','Ja Morant'), ('Towns','Karl-Anthony Towns'), ('Allen','Jarrett Allen'), ('Curry','Stephen Curry'), ('Paul','Chris Paul'), ('Harden','James Harden'), ('Murray','Dejounte Murray'), ('Garland','Darius Garland'), ('Ball','Lamelo Ball'), ('Wiggins','Andrew Wiggins'), ('Green','Draymond Green'), ('Lavine','Zach Lavine'), ('VanVleet','Fred VanVleet'), ('Butler','Jimmy Butler'), ('Middleton','Khris Middleton'), ('Mitchell','Donovan Mitchell')], validators=[DataRequired()])
    submit = SubmitField()

